# Generated by Django 5.2.7 on 2025-10-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tieba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='贴吧名称')),
                ('description', models.TextField(max_length=500, verbose_name='贴吧描述')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='tieba_avatars/', verbose_name='贴吧头像')),
                ('member_count', models.PositiveIntegerField(default=0, verbose_name='成员数')),
                ('post_count', models.PositiveIntegerField(default=0, verbose_name='帖子数')),
                ('today_post_count', models.PositiveIntegerField(default=0, verbose_name='今日发帖数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('is_official', models.BooleanField(default=False, verbose_name='是否官方贴吧')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '贴吧',
                'verbose_name_plural': '贴吧',
                'db_table': 'tiebas',
                'ordering': ['-member_count'],
            },
        ),
        migrations.CreateModel(
            name='TiebaAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('announcement_type', models.CharField(choices=[('normal', '普通公告'), ('important', '重要公告'), ('event', '活动公告')], default='normal', max_length=20, verbose_name='公告类型')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '贴吧公告',
                'verbose_name_plural': '贴吧公告',
                'db_table': 'tieba_announcements',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TiebaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='分类描述')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='分类图标')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '贴吧分类',
                'verbose_name_plural': '贴吧分类',
                'db_table': 'tieba_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TiebaMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', '普通成员'), ('moderator', '吧务'), ('admin', '吧主')], default='member', max_length=20, verbose_name='角色')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='最后活跃时间')),
                ('contribution_score', models.PositiveIntegerField(default=0, verbose_name='贡献度')),
            ],
            options={
                'verbose_name': '贴吧成员',
                'verbose_name_plural': '贴吧成员',
                'db_table': 'tieba_memberships',
                'ordering': ['-contribution_score'],
            },
        ),
        migrations.CreateModel(
            name='TiebaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='规则标题')),
                ('content', models.TextField(verbose_name='规则内容')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '贴吧规则',
                'verbose_name_plural': '贴吧规则',
                'db_table': 'tieba_rules',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
