# Generated by Django 5.2.7 on 2025-10-29 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiebas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tieba',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tiebas', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='tieba',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_tiebas', to=settings.AUTH_USER_MODEL, verbose_name='吧务团队'),
        ),
        migrations.AddField(
            model_name='tiebaannouncement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='tiebaannouncement',
            name='tieba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='tiebas.tieba', verbose_name='贴吧'),
        ),
        migrations.AddField(
            model_name='tiebamembership',
            name='tieba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiebas.tieba', verbose_name='贴吧'),
        ),
        migrations.AddField(
            model_name='tiebamembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='tiebarule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='tiebarule',
            name='tieba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='tiebas.tieba', verbose_name='贴吧'),
        ),
        migrations.AlterUniqueTogether(
            name='tiebamembership',
            unique_together={('user', 'tieba')},
        ),
    ]
