# Generated by Django 5.2.7 on 2025-10-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='帖子标题')),
                ('content', models.TextField(verbose_name='帖子内容')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('reply_count', models.PositiveIntegerField(default=0, verbose_name='回复数')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('collect_count', models.PositiveIntegerField(default=0, verbose_name='收藏数')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('is_essence', models.BooleanField(default=False, verbose_name='是否精华')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_reply_at', models.DateTimeField(auto_now_add=True, verbose_name='最后回复时间')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'db_table': 'posts',
                'ordering': ['-is_pinned', '-last_reply_at'],
            },
        ),
        migrations.CreateModel(
            name='PostCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
            ],
            options={
                'verbose_name': '帖子收藏',
                'verbose_name_plural': '帖子收藏',
                'db_table': 'post_collects',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/', verbose_name='图片')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='图片描述')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '帖子图片',
                'verbose_name_plural': '帖子图片',
                'db_table': 'post_images',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
            ],
            options={
                'verbose_name': '帖子点赞',
                'verbose_name_plural': '帖子点赞',
                'db_table': 'post_likes',
            },
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('spam', '垃圾广告'), ('inappropriate', '内容不适宜'), ('illegal', '违法违规'), ('harassment', '骚扰谩骂'), ('other', '其他原因')], max_length=20, verbose_name='举报类型')),
                ('description', models.TextField(blank=True, verbose_name='举报描述')),
                ('is_handled', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
            ],
            options={
                'verbose_name': '帖子举报',
                'verbose_name_plural': '帖子举报',
                'db_table': 'post_reports',
            },
        ),
    ]
